"""
NPZ episode loading.

This module is the single point of contact between raw .npz files on disk
and the rest of the framework.  All field name assumptions and joint-ordering
logic live here, so changing the data format only requires edits in this file.

Expected NPZ structure
----------------------
Required fields:
    joint_positions     (T,) array of dicts   OR  (T, 30) float array
    joint_efforts       (T, 30) float array
    joint_velocities    (T, 30) float array

Optional visual fields (present when cameras are used):
    images_cam0 … images_cam{N-1}   (T, H, W, 3) uint8
    depth_cam0  … depth_cam{N-1}    (T, H, W) uint16 / float

Optional tactile:
    tactile_states   (T, 60) float

Optional pre-computed visual features (generated by the pre-computation
script, saved alongside the NPZ):
    rgb_features_cam0 … rgb_features_cam{N-1}  (T, raw_dim) float
"""

from __future__ import annotations

import os
import concurrent.futures
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

import natsort
import numpy as np

# ---------------------------------------------------------------------------
# Joint ordering (30-DOF Shadow Hand + UR arm system)
# ---------------------------------------------------------------------------

_JOINT_ORDER = [
    # UR arm (6 DOF)
    "ra_shoulder_pan_joint", "ra_shoulder_lift_joint", "ra_elbow_joint",
    "ra_wrist_1_joint",      "ra_wrist_2_joint",       "ra_wrist_3_joint",
    # Shadow Hand (24 DOF)
    "rh_FFJ1", "rh_FFJ2", "rh_FFJ3", "rh_FFJ4",
    "rh_MFJ1", "rh_MFJ2", "rh_MFJ3", "rh_MFJ4",
    "rh_RFJ1", "rh_RFJ2", "rh_RFJ3", "rh_RFJ4",
    "rh_LFJ1", "rh_LFJ2", "rh_LFJ3", "rh_LFJ4", "rh_LFJ5",
    "rh_THJ1", "rh_THJ2", "rh_THJ3", "rh_THJ4", "rh_THJ5",
    "rh_WRJ1", "rh_WRJ2",
]
assert len(_JOINT_ORDER) == 30, "Joint order must have exactly 30 joints."

ARM_SLICE  = slice(0, 6)    # indices for UR arm joints
HAND_SLICE = slice(6, 30)   # indices for Shadow Hand joints


# ---------------------------------------------------------------------------
# Joint position extraction
# ---------------------------------------------------------------------------

def _extract_joint_array(raw: np.ndarray, default_key: str | None = None) -> np.ndarray:
    """
    Convert a raw joint array from an NPZ file to a (T, 30) float32 array.

    Handles two formats:
      - (T,) array of dicts  — each dict maps joint name → float value
      - (T, D) float array   — already dense; pads/clips to 30 dims

    *default_key* is used when a dict value is itself a dict (e.g.
    ``{"position": 1.23}``).  For ``joint_positions`` pass ``"position"``;
    for other fields it is rarely needed.
    """
    if raw.ndim == 1 and isinstance(raw[0], dict):
        rows = []
        for d in raw:
            if d is None:
                d = {}
            row = []
            for j in _JOINT_ORDER:
                v = d.get(j, 0.0)
                if isinstance(v, dict):
                    v = v.get(default_key, 0.0) if default_key else 0.0
                row.append(float(v))
            rows.append(row)
        return np.array(rows, dtype=np.float32)

    arr = np.asarray(raw, dtype=np.float32)
    if arr.ndim == 1:
        arr = arr[np.newaxis, :]   # single timestep
    T, D = arr.shape
    if D != 30:
        padded = np.zeros((T, 30), dtype=np.float32)
        padded[:, : min(D, 30)] = arr[:, : min(D, 30)]
        return padded
    return arr


def _extract_joint_positions(raw: np.ndarray) -> np.ndarray:
    """Convenience wrapper — extracts joint positions (T, 30)."""
    return _extract_joint_array(raw, default_key="position")


# ---------------------------------------------------------------------------
# Single-episode loader
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Dual-format loader (NPZ files or .npy directories)
# ---------------------------------------------------------------------------

class _EpisodeData:
    """Thin wrapper that loads arrays from either .npz or .npy directory."""

    def __init__(self, path: Path):
        self._path = path
        if path.is_dir():
            # .npy directory format
            self._mode = "npy"
            self._keys = [p.stem for p in path.glob("*.npy")]
        else:
            # .npz file format
            self._mode = "npz"
            self._npz = np.load(str(path), allow_pickle=True)
            self._keys = list(self._npz.files)

    def __contains__(self, key: str) -> bool:
        if self._mode == "npy":
            return (self._path / f"{key}.npy").exists()
        return key in self._npz

    def __getitem__(self, key: str) -> np.ndarray:
        if self._mode == "npy":
            return np.load(self._path / f"{key}.npy", allow_pickle=True)
        return self._npz[key]

    @property
    def files(self) -> list[str]:
        return self._keys


def load_episode(
    path: str | Path,
    representation_type: list[str],
    camera_indices: list[int],
    load_img: bool = True,
    feature_path: str | Path | None = None,
) -> dict[str, np.ndarray]:
    """
    Load one episode into a flat dict of numpy arrays.

    Supports both .npz files and .npy directories (a directory containing
    individual ``{array_name}.npy`` files).

    The returned dict uses the **canonical batch keys** defined in
    PolicyModel's docstring, so datasets and models share the same names.

    Args:
        path:                Path to the .npz file or .npy directory.
        representation_type: Which modalities to load.
                             Subset of ["img", "depth", "pos", "eef",
                             "hand_pos", "efforts", "velocity", "touch"].
        camera_indices:      Which camera streams to include.
        load_img:            If False, skip loading image arrays (useful
                             when only pre-computed features are needed).
        feature_path:        Path to a separate feature file/dir (output of
                             precompute_features.py). When provided, rgb_features
                             are loaded from this instead of from *path*.

    Returns:
        Dict of (T, ...) numpy arrays keyed by canonical names.
    """
    data = _EpisodeData(Path(path))
    episode: dict[str, np.ndarray] = {}

    # ---- Actions / joint positions (always loaded) ----
    joint_pos = _extract_joint_positions(data["joint_positions"])   # (T, 30)
    episode["action"] = joint_pos   # actions = joint positions of that step

    # ---- Proprioception ----
    needs_joints = any(k in representation_type for k in ("pos", "eef", "hand_pos"))
    if needs_joints:
        if "pos" in representation_type:
            episode["pos"] = joint_pos
        if "eef" in representation_type:
            episode["eef"] = joint_pos[:, ARM_SLICE]       # (T, 6)
        if "hand_pos" in representation_type:
            episode["hand_pos"] = joint_pos[:, HAND_SLICE] # (T, 24)

    if "efforts" in representation_type and "joint_efforts" in data:
        eff = _extract_joint_array(data["joint_efforts"])   # (T, 30)
        if eff.shape[-1] >= 30:
            episode["efforts"] = eff[:, HAND_SLICE]        # (T, 24) hand only
        else:
            episode["efforts"] = eff

    if "velocity" in representation_type and "joint_velocities" in data:
        episode["velocity"] = _extract_joint_array(data["joint_velocities"])  # (T, 30)

    if "touch" in representation_type and "tactile_states" in data:
        episode["touch"] = np.asarray(data["tactile_states"], dtype=np.float32)

    # ---- Visual ----
    if load_img:
        if "img" in representation_type:
            for cam in camera_indices:
                key = f"images_cam{cam}"
                if key in data:
                    episode[f"rgb_cam{cam}"] = np.asarray(data[key], dtype=np.uint8)

        if "depth" in representation_type:
            for cam in camera_indices:
                key = f"depth_cam{cam}"
                if key in data:
                    episode[f"depth_cam{cam}"] = np.asarray(data[key], dtype=np.float32)

    # ---- Pre-computed RGB features ----
    feat_data = data
    if feature_path is not None and Path(feature_path).exists():
        feat_data = _EpisodeData(Path(feature_path))
    for cam in camera_indices:
        feat_key = f"rgb_features_cam{cam}"
        if feat_key in feat_data:
            episode[feat_key] = np.asarray(feat_data[feat_key], dtype=np.float32)

    return episode


# ---------------------------------------------------------------------------
# Instruction extraction from path
# ---------------------------------------------------------------------------

def extract_instruction_from_path(path: str | Path) -> int | None:
    """
    Infer the integer instruction ID from the directory structure.

    Convention: the instruction ID is the name of the direct parent directory
    of the ``*_train*`` or ``*_test*`` folder.

        .../easy_mode/5/pick_up_card_train_50/data0001.npz  →  5

    Returns None when no ``*_train*`` or ``*_test*`` directory is found.
    Raises ValueError when such a directory is found but its direct parent
    is not an integer instruction ID.
    """
    parts = Path(path).parts
    for i, part in enumerate(parts):
        if "_train" in part or "_test" in part:
            if i > 0:
                try:
                    return int(parts[i - 1])
                except ValueError:
                    # Parent paths such as ".tmp_test" or "unit_test_runs" can
                    # contain the same marker. Keep scanning for the actual
                    # split directory whose parent is the numeric instruction.
                    continue
    return None


# ---------------------------------------------------------------------------
# Episode discovery (supports .npz files and .npy directories)
# ---------------------------------------------------------------------------

def _find_episodes(data_dir: Path) -> list[Path]:
    """Find all episode paths in *data_dir* (both .npz and .npy dir formats).

    Returns a sorted list of paths — either ``data*.npz`` files or
    ``data*`` directories containing ``.npy`` files.
    """
    # .npy directories: data0001/, data0002/, ...
    npy_dirs = [d for d in data_dir.iterdir()
                if d.is_dir() and d.name.startswith("data")
                and any(d.glob("*.npy"))]
    # .npz files: data0001.npz, data0002.npz, ...
    npz_files = list(data_dir.glob("data*.npz"))

    episodes = npy_dirs + npz_files
    if not episodes:
        raise FileNotFoundError(
            f"No episodes found in {data_dir} "
            "(expected data*.npz files or data*/ directories with .npy files)")
    return natsort.natsorted(episodes, key=lambda p: str(p))


def _feature_path_for(episode_path: Path, feature_dir: Path) -> Path | None:
    """Map an episode path to its corresponding feature path."""
    if feature_dir is None:
        return None
    # data0001.npz → feature_dir/data0001.npz or data0001/
    # data0001/    → feature_dir/data0001/ or data0001.npz
    name = episode_path.stem if episode_path.suffix == ".npz" else episode_path.name
    # Try directory first, then .npz
    d = feature_dir / name
    if d.exists():
        return d
    f = feature_dir / f"{name}.npz"
    if f.exists():
        return f
    return None


# ---------------------------------------------------------------------------
# Dataset iterator (multi-episode, parallel loading)
# ---------------------------------------------------------------------------

def iterate_dataset(
    data_dir: str | Path,
    representation_type: list[str],
    camera_indices: list[int],
    load_img: bool = True,
    n_workers: int = 4,
    feature_dir: str | Path | None = None,
) -> tuple[dict[str, np.ndarray], np.ndarray, list[int | None]]:
    """
    Load all .npz files in *data_dir* in parallel and concatenate them into
    a single flat buffer suitable for ``RobotDataset``.

    Args:
        data_dir:            Directory containing ``data*.npz`` files.
        representation_type: Which modalities to load (see ``load_episode``).
        camera_indices:      Which cameras to include.
        load_img:            Whether to load raw images.
        n_workers:           Thread pool size for parallel loading.
        feature_dir:         Directory containing feature NPZ files that mirror
                             *data_dir* (output of precompute_features.py).
                             Feature file for ``data_dir/dataXXXX.npz`` is
                             ``feature_dir/dataXXXX.npz``.

    Returns:
        data_buffer:   Flat dict of concatenated (N_total, ...) arrays.
        episode_ends:  (num_episodes,) cumulative end indices.
        instructions:  Per-episode instruction ID (or None if not found).
    """
    data_dir = Path(data_dir)
    episode_paths = _find_episodes(data_dir)

    _feature_dir = Path(feature_dir) if feature_dir else None

    def _load(p: Path) -> dict[str, np.ndarray]:
        feat_path = _feature_path_for(p, _feature_dir)
        return load_episode(p, representation_type, camera_indices, load_img,
                            feature_path=feat_path)

    from tqdm import tqdm

    n = len(episode_paths)
    episodes: list[dict[str, np.ndarray]] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, n_workers)) as pool:
        futures = {pool.submit(_load, p): p for p in episode_paths}
        for fut in tqdm(concurrent.futures.as_completed(futures), total=n,
                        unit="ep", desc=f"Loading {data_dir.name}"):
            path = futures[fut]
            try:
                episodes.append((path, fut.result()))
            except Exception as exc:
                print(f"[WARNING] Failed to load {path}: {exc}")

    # Sort back to file order (as_completed gives arbitrary ordering).
    episodes.sort(key=lambda x: str(x[0]))
    if not episodes:
        raise RuntimeError(
            f"All episodes in {data_dir} failed to load. "
            "Check the warnings above for details."
        )
    paths, episodes = zip(*episodes)

    # Concatenate into flat buffers.
    all_keys = {key for ep in episodes for key in ep}
    flat_buffer: dict[str, np.ndarray] = {}
    for key in all_keys:
        parts = [ep[key] for ep in episodes if key in ep]
        if parts:
            flat_buffer[key] = np.concatenate(parts, axis=0)

    # Episode boundary indices (action is always small, never mmap'd).
    lengths = [ep["action"].shape[0] if "action" in ep else 0 for ep in episodes]
    episode_ends = np.cumsum(lengths).astype(np.int64)

    # Per-episode instruction IDs.
    instructions = [extract_instruction_from_path(p) for p in paths]

    return flat_buffer, episode_ends, instructions


# ---------------------------------------------------------------------------
# Lazy dataset index builder (proprioception only — no images in RAM)
# ---------------------------------------------------------------------------

@dataclass
class _EpisodeIndex:
    """Lightweight metadata for one episode, used by lazy loading."""
    path: Path
    feature_path: Path | None
    length: int
    instruction: int | None
    is_dir: bool = False           # True if .npy directory format
    feat_is_dir: bool = False      # True if feature path is a directory


@dataclass
class LazyDatasetIndex:
    """Index for lazy-loaded dataset.

    Holds per-episode file paths and lengths, plus concatenated
    proprioception arrays (tiny) used to compute normalization stats.
    """
    episodes: list[_EpisodeIndex]
    episode_ends: np.ndarray          # (num_episodes,) cumulative
    prop_buffer: dict[str, np.ndarray]  # concatenated proprioception only
    representation_type: list[str]
    camera_indices: list[int]


def _load_episode_proprioception(
    path: Path,
    representation_type: list[str],
    feature_path: Path | None = None,
) -> dict[str, np.ndarray]:
    """Load only proprioception + actions from an episode (no images)."""
    data = _EpisodeData(Path(path))
    episode: dict[str, np.ndarray] = {}

    joint_pos = _extract_joint_positions(data["joint_positions"])
    episode["action"] = joint_pos

    needs_joints = any(k in representation_type for k in ("pos", "eef", "hand_pos"))
    if needs_joints:
        if "pos" in representation_type:
            episode["pos"] = joint_pos
        if "eef" in representation_type:
            episode["eef"] = joint_pos[:, ARM_SLICE]
        if "hand_pos" in representation_type:
            episode["hand_pos"] = joint_pos[:, HAND_SLICE]

    if "efforts" in representation_type and "joint_efforts" in data:
        eff = _extract_joint_array(data["joint_efforts"])
        if eff.shape[-1] >= 30:
            episode["efforts"] = eff[:, HAND_SLICE]
        else:
            episode["efforts"] = eff

    if "velocity" in representation_type and "joint_velocities" in data:
        episode["velocity"] = _extract_joint_array(data["joint_velocities"])

    if "touch" in representation_type and "tactile_states" in data:
        episode["touch"] = np.asarray(data["tactile_states"], dtype=np.float32)

    return episode


def iterate_dataset_lazy(
    data_dir: str | Path,
    representation_type: list[str],
    camera_indices: list[int],
    n_workers: int = 4,
    feature_dir: str | Path | None = None,
) -> LazyDatasetIndex:
    """Build an index for lazy loading — only proprioception is loaded into RAM.

    Images / depth / features are NOT loaded.  They will be read on-demand
    in ``LazyRobotDataset.__getitem__`` from uncompressed NPZ files.

    Returns:
        A ``LazyDatasetIndex`` with episode metadata, cumulative ends,
        and concatenated proprioception arrays for normalization.
    """
    data_dir = Path(data_dir)
    episode_paths = _find_episodes(data_dir)

    _feature_dir = Path(feature_dir) if feature_dir else None

    from tqdm import tqdm

    def _load(p: Path):
        feat_path = _feature_path_for(p, _feature_dir)
        prop = _load_episode_proprioception(p, representation_type, feat_path)
        return p, feat_path, prop

    n = len(episode_paths)
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, n_workers)) as pool:
        futures = {pool.submit(_load, p): p for p in episode_paths}
        for fut in tqdm(concurrent.futures.as_completed(futures), total=n,
                        unit="ep", desc=f"Indexing {data_dir.name}"):
            try:
                results.append(fut.result())
            except Exception as exc:
                print(f"[WARNING] Failed to index {futures[fut]}: {exc}")

    results.sort(key=lambda x: str(x[0]))

    ep_indices: list[_EpisodeIndex] = []
    prop_parts: dict[str, list[np.ndarray]] = {}

    for path, feat_path, prop in results:
        length = prop["action"].shape[0]
        instr = extract_instruction_from_path(path)
        ep_indices.append(_EpisodeIndex(
            path, feat_path, length, instr,
            is_dir=path.is_dir(),
            feat_is_dir=feat_path.is_dir() if feat_path else False,
        ))
        for k, v in prop.items():
            prop_parts.setdefault(k, []).append(v)

    prop_buffer = {k: np.concatenate(parts, axis=0) for k, parts in prop_parts.items()}
    lengths = [e.length for e in ep_indices]
    episode_ends = np.cumsum(lengths).astype(np.int64)

    return LazyDatasetIndex(
        episodes=ep_indices,
        episode_ends=episode_ends,
        prop_buffer=prop_buffer,
        representation_type=representation_type,
        camera_indices=camera_indices,
    )
